#include <backend.h>
#include <version.h>

static int usable_registers[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 };
static string quadword_registers[] = { "x0", "x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10", "x11", "x12" };

static int return_register = 0;
static FILE* backend_out = NULL;

void emit_arm64_function(function_t* func);
void emit_arm64_return(statement_t* stmt);

void arm64_assert(compilation_unit_t* code, int condition, string str, size_t line, size_t column, string item) {
    if (condition) 
        return;

    fprintf(stderr, 
            "%s:%zu:%zu: \033[1;31mcodegen error:\033[0m %s\n"
            "  %zu  |  %s\n", 
            code->in_file, line, column, str,
            line, item);

    int digits = COUNTDIGITSU(line) + 4; // Account for spaces
    for (int i = 0; i < digits; i++)
        putc(' ', stderr);
    
    fprintf(stderr, "|  \033[1;31m^");

    size_t len = strlen(item) - 1;

    for (size_t i = 0; i < len; i++)
        putc('~', stderr);

    puts("\033[0m");
    
    exit(-1); 
}

bool run_arm64_backend(compilation_unit_t* unit) {
    (void)usable_registers;

    if (!unit) return false;

    if (unit->out_file && unit->out_file[0] != '\0') {
        backend_out = fopen(unit->out_file, "w");
        if (!backend_out) {
            perror("fopen");
            return false;
        }
    } else {
        backend_out = stdout;
    }

    fprintf(backend_out, "// Generated by ACC %s\n\n", ACC_VERSION);
    fprintf(backend_out, ".file \"%s\"\n\n", unit->in_file);
    fprintf(backend_out, ".ofile \"%s\"\n\n", unit->out_file);
    fprintf(backend_out, ".text\n\n");

    for (size_t i = 0; i < unit->parser->function_count; i++) {
        function_t func = unit->parser->functions[i];
        emit_arm64_function(&func);
    }

    if (backend_out && backend_out != stdout) {
        fclose(backend_out);
    }
    backend_out = NULL;

    return true;
}

void emit_arm64_return(statement_t* stmt) {
    if (!stmt) return;
    if (stmt->return_state.type == TOK_LITERAL) {
        fprintf(backend_out, "  mov %s, #%lld\n", quadword_registers[return_register], stmt->return_state.int_type);
    }
    fprintf(backend_out, "  ret\n");
}

void emit_arm64_function(function_t* func) {
    if (!func) return;
    fprintf(backend_out, "_%s:\n", func->name);
    for (size_t i = 0; i < func->body.statement_count; i++) {
        statement_t stmt = func->body.statments[i];
        if (stmt.type == STATE_RETURN) {
            emit_arm64_return(&stmt);
        }
    }
}
